---

- hosts: all
  become: yes
  roles:
    - { role: docker_remove, when: remove is defined }
    - { role: docker_common, when: common is defined }
    - { role: docker_compose, when: compose is defined }
    - { role: docker_machine, when: machine is defined }
