---

- hosts: all
  become: yes
  roles:
    - { role: remove, when: remove is defined }
    - { role: common, when: common is defined }
    - { role: compose, when: compose is defined }
    - { role: machine, when: machine is defined }
