---

- name: stop docker
  systemd:
    name: docker
    state: stopped
    enabled: false

- name: remove everything
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ remove_things }}"

- name: remove everything_2
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ remove_things2 }}"