---
# tasks file for common
- name: install epel release
  yum: "{{ item.name }}"
  state: "{{ item.state }}"
  when: uninstall_everything is defined
  with_items:
    - "{{ yum_epel_release }}"

- name: remove everything
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  when: uninstall_everything is defined
  with_items:
    - "{{ remove_things }}"

- name: install stuff
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ prerequisite_for_repo }}"
  when: prereq_install is defined
  
- name: configure repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: configure_repo is defined

- name: install docker-ce
  yum:
    name: docker-ce
    state: present
  notify:
    - start docker    
  when: install_docker_ce is defined
  register: docker_ce_installed

- name: add user to docker group
  command: usermod -aG docker {{ ansible_user }}
  when: docker_ce_installed.changed == true

- name: add bash_completion package
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ yum_bash_completion }}"

- name: add bash completion
  command: curl -L https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker -o /etc/bash_completion.d/docker